### ISSUE TITLE
能否支持从本地读取txt形式的直播源呢

### ISSUE THREAD

**Issue by nankaine** [kimwang1978/collect-tv-txt#1]
你好，在线的方式挺不错的。
但是有些直播源在本地是txt形式存在的，能否支持一下从本地读取，而非从在线链接获取。 谢谢

**Comment by kimwang1978** [comment]
> 你好，在线的方式挺不错的。 但是有些直播源在本地是txt形式存在的，能否支持一下从本地读取，而非从在线链接获取。 谢谢

在线的好处是每天自动更新，有些无效的直播源慢慢会被剔除掉，本地txt一段时间不更新有些源就失效了。本地的话，你可以直接把merged_output.txt（该文件每天早上自动更新）文件下载到本地，再导入到本地壳播放器中，等有些源用不了再过来下载最新的。

**Comment by kimwang1978** [comment]
> > > 你好，在线的方式挺不错的。 但是有些直播源在本地是txt形式存在的，能否支持一下从本地读取，而非从在线链接获取。 谢谢
> > 
> > 
> > 在线的好处是每天自动更新，有些无效的直播源慢慢会被剔除掉，本地txt一段时间不更新有些源就失效了。本地的话，你可以直接把merged_output.txt（该文件每天早上自动更新）文件下载到本地，再导入到本地壳播放器中，等有些源用不了再过来下载最新的。
> 
> 开一下库的 Discussions 吧，有些问题可能不适合发到issue里面

@nankaine  现在开了
