### ISSUE TITLE
上海频道 失效了

### ISSUE THREAD

**Issue by xmaec555** [kimwang1978/collect-tv-txt#12]
上海频道 删除 把中央放一位 可以吗

**Comment by kimwang1978** [comment]
@xmaec555 把上海频道调到卫视后面了，央视现在在最上面，明天自动更新后就可以看到。

**Comment by kimwang1978** [comment]
@xmaec555 另外，上海频道没有失效，每个频道都有多个源，昨晚排在第一源都不行，切到第二个源就能正常播放。

**Comment by xmaec555** [comment]
你好， 一直在用你的直播源， 能不能增加福建地区的频道

**Comment by xmaec555** [comment]
福建频道 电台太少了

**Comment by kimwang1978** [comment]
@xmaec555  好的，这几天就来整理一下。
