### ISSUE TITLE
http://gg.gg/tv-live-txt unavailable now

### ISSUE THREAD

**Issue by wnpllrzodiac** [kimwang1978/collect-tv-txt#13]
503 Service Unavailable

Server could not complete your request. Might be a good idea to check back later

**Comment by kimwang1978** [comment]
我看看

**Comment by kimwang1978** [comment]
好像短链服务器被攻击了，也不知道什么时候能恢复。

你可以先用这个短链：https://go.click.ly/inwPk
或者直接用这个：https://ghproxy.net/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt

**Comment by wnpllrzodiac** [comment]
> 好像短链服务器被攻击了，也不知道什么时候能恢复。
> 
> 你可以先用这个短链：https://go.click.ly/inwPk 或者直接用这个：https://ghproxy.net/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt

是gdzj么。。。为啥干你的txt

**Comment by kimwang1978** [comment]
应该不是针对我吧…我这就是纯娱乐…可能是短链服务器被人盯上了，先观察观察，不行就只能放弃这个短链了

**Comment by kimwang1978** [comment]
难道真被人盯上了  😳

**Comment by kimwang1978** [comment]
gg.gg今天恢复了
