### ISSUE TITLE
老哥，可以加多点广东的卫视吗，比如汕头卫视1，2，3，还有香港的翡翠卫视不稳定，能处理吗，辛苦辛苦

### ISSUE THREAD

**Issue by haohuaZhang** [kimwang1978/collect-tv-txt#14]

**Comment by haohuaZhang** [comment]
@kimwang1978

**Comment by kimwang1978** [comment]
好的，我找找添加进来。
@haohuaZhang

**Comment by haohuaZhang** [comment]
> 好的，我找找添加进来。
> @haohuaZhang 

辛苦辛苦

**Comment by haohuaZhang** [comment]
> > > 好的，我找找添加进来。
> > > @haohuaZhang
> > 
> > 辛苦辛苦
> 
> @haohuaZhang 整理了一下广东频道，明天中午看效果怎么样。

好的，老哥牛逼

**Comment by haohuaZhang** [comment]
> > > > 好的，我找找添加进来。
> > > > @haohuaZhang
> > > 
> > > 辛苦辛苦
> > 
> > @haohuaZhang 整理了一下广东频道，明天中午看效果怎么样。
> 
> 好的，老哥牛逼

翡翠台也麻烦一下哈老哥

**Comment by kimwang1978** [comment]
> > > > > 好的，我找找添加进来。
> > > > > @haohuaZhang
> > > > 
> > > > 
> > > > 辛苦辛苦
> > > 
> > > 
> > > @haohuaZhang 整理了一下广东频道，明天中午看效果怎么样。
> > 
> > 
> > 好的，老哥牛逼
> 
> 翡翠台也麻烦一下哈老哥

公众号已经回复了，今天的翡翠台里有高质量的线路，你换几次线路就找到了，非常清晰流畅，前面看了半小时多。

**Comment by kimwang1978** [comment]
> > > > > 好的，我找找添加进来。
> > > > > @haohuaZhang
> > > > 
> > > > 
> > > > 辛苦辛苦
> > > 
> > > 
> > > @haohuaZhang 整理了一下广东频道，明天中午看效果怎么样。
> > 
> > 
> > 好的，老哥牛逼
> 
> 翡翠台也麻烦一下哈老哥

挑了一些翡翠台比较快的源放到优质源组里了，这几天可以观察一下效果好不好。

**Comment by haohuaZhang** [comment]
> > > > > > 好的，我找找添加进来。
> > > > > > @haohuaZhang
> > > > > 
> > > > > 
> > > > > 辛苦辛苦
> > > > 
> > > > 
> > > > @haohuaZhang 整理了一下广东频道，明天中午看效果怎么样。
> > > 
> > > 
> > > 好的，老哥牛逼
> > 
> > 
> > 翡翠台也麻烦一下哈老哥
> 
> 挑了一些翡翠台比较快的源放到优质源组里了，这几天可以观察一下效果好不好。

老哥🐮🍺
