### ISSUE TITLE
这个列表有大量的源，可否做为上游

### ISSUE THREAD

**Issue by vbskycn** [kimwang1978/collect-tv-txt#15]
https://freetv.fun/test_channels_original_new.txt

**Comment by kimwang1978** [comment]
@vbskycn 收到，多谢，我来看看！

**Comment by kimwang1978** [comment]
> https://freetv.fun/test_channels_original_new.txt

这段时间看了一下，里面确实有些源不错，不过参差不齐，质量好的和质量差的差好多，需要有时间专门先做预处理再作为上游源，考虑考虑。

**Comment by vbskycn** [comment]
感谢大佬，确实需要脚本过滤一下，奈何水平太菜，写不出好的脚本。

**Comment by kimwang1978** [comment]
> 感谢大佬，确实需要脚本过滤一下，奈何水平太菜，写不出好的脚本。

简单写了个脚本初步过滤了一下，在assets目录下，freetv_output.txt是跑好之后的样子，脚本你可以直接拿去改了自己用，或者再慢慢等我有时间再改得完善些。另外，freetv这个txt更新频率你清楚吗？

**Comment by vbskycn** [comment]
感谢大佬
