### ISSUE TITLE
ipv4

### ISSUE THREAD

**Issue by SUZQC** [kimwang1978/collect-tv-txt#26]
IPTV的ipv4几乎是没有的，ipv6完美，可惜我的盒子获取不了dns
![mmexport1731121531067](https://github.com/user-attachments/assets/610ba359-6252-4959-a6b5-a5e3bcf75319)
![Screenshot_2024-11-09-23-40-09-643_com vphonegaga titan](https://github.com/user-attachments/assets/cf6fb431-8e5f-4ad5-98b1-54c0cc4ed7c3)

**Comment by kimwang1978** [comment]
好的，留意多加些v4的。

另外，按照下面试试看，能不能解决v6的问题。
https://test-ipv6.com/faq_broken_aaaa.html.zh_CN
https://github.com/XX-net/XX-Net/issues/7167

**Comment by SUZQC** [comment]
我去完全没注意到作者居然回我了，谢谢啦
