### ISSUE TITLE
检测m3u

### ISSUE THREAD

**Issue by liuyug** [kimwang1978/collect-tv-txt#4]
收集到的直播源好多都是无效的，请求加入检测功能，去除失效的直播源

**Comment by kimwang1978** [comment]
> 收集到的直播源好多都是无效的，请求加入检测功能，去除失效的直播源

本来想早点加，由于源地址比较多，听说免费的github actions如果发现你网络访问量过多的话可能会威胁到帐号（直白地说就是帐号被禁）……
容我构思一下，看看有没有折中的办法。

**Comment by kimwang1978** [comment]
从今天开始加入了blacklist处理，blacklist里的源都会被过滤掉，我会不定期在本地维护这个blacklist，这样能提高源的有效性。
blacklist.py就用来在本地检测自动整理blacklist，这样就规避了中actions中大量访问不同ip触发github自动检测，降低帐号的危险性。

**Comment by kimwang1978** [comment]
> 收集到的直播源好多都是无效的，请求加入检测功能，去除失效的直播源

@liuyug 这几天blacklist运行得不错，这个issue先关了。
