### ISSUE TITLE
增加节目数量、还有节目去重

### ISSUE THREAD

**Issue by xuy132** [kimwang1978/collect-tv-txt#5]
增加节目数量如：各地卫视、各地地方台
再加一个节目去重功能。很多地址重复。

**Comment by xuy132** [comment]
还有河南河北与湖南湖北，字母省略是一样。

**Comment by kimwang1978** [comment]
好的，找时间整理一下。
现在是卫视放在一起，各个地方以省为单位把地方台都塞在里面，有点乱，慢慢整理，如果有好的分类建议欢迎提。
重复的地址确实有，这个确实要处理一下。

**Comment by kimwang1978** [comment]
@xuy132 大部分地方台加进来了，明天能看到效果。你那个pr里面有太多没法合并的内容，方便起见从里面扣出了大部分内容。
去重已经在check_url_existence里实现了，如果发现相同的url直接跳过不会加入进来。

无法使用地址的已经在blacklist文件里实现，目前两天本地执行一次结果会checkin到线上，github里免费action的不能check太多url，容易违规。

**Comment by xuy132** [comment]
本来思路采集github所有IPTV可用地址，但是后面发现节目源都存在不能播放，导致央视特别多节目源整个读取卡顿。听说节目源条目数不超过2000，就很好。
还有比如春晚、DJ舞曲、韩国女团那种固定节目，也找到了很多（16万KTV必点歌曲）。这种是不是建一个类目。
还有影视点播和明星频道两个存在共同。

**Comment by kimwang1978** [comment]
@xuy132 好的，慢慢都来加上。
